; Projeto PlatformIO - Fita WS2812B com 3 segmentos (3 fios de dados)
; ESP32 Devkit / ESP32 WROOM 32

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    fastled/FastLED@^3.7.0

; Descomente e ajuste se a porta nao for detectada automaticamente
; upload_port = COM3
; monitor_port = COM3
