; Projeto PlatformIO - Controle de motor linear via BTS7960
; ESP32 Devkit

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

; Descomente e ajuste se a porta nao for detectada automaticamente
; upload_port = COM3
; monitor_port = COM3
